steps:
#- name: 'gcr.io/cloud-builders/docker'
#  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/quickstart-image', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker build --build-arg="GOPRIVATE=source.developers.google.com" -t gcr.io/$PROJECT_ID/quickstart-image:latest .']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/taos-macleish-la/quickstart-image']
#- name: 'gcr.io/cloud-builders/gcloud'
#  args: ['app','deploy','--image-url=gcr.io/taos-macleish-la/quickstart-image']
timeout: 1600s
#images:
#- 'gcr.io/$PROJECT_ID/quickstart-image'
